porter:
  barn: /data/barn

rabbitmq:
  address: "localhost"
  queue: "file_list"

video_types: ["avi", "mp4"]

image_types: ["jpg", "jpeg", "png", "gif", "bmp"]

monitor:
  timeout: 30
  max_num_try: 3

mongodb:
  host: localhost
  port: 27017
  username: "mongoadmin"
  password: "secret"
  db_name: "dwarf"