dirs:
  barn: /data/barn
  warehouse: /data/warehouse 

rabbitmq:
  address: "localhost"
  queue: "dwarf"

video_types: ["avi", "mp4"]

image_types: ["jpg", "jpeg", "png", "gif", "bmp"]

monitor:
  timeout: 30
  max_num_try: 3

mongodb:
  host: "localhost"
  port: 27017
  username: "dwarf"
  password: "secret"
  name: "dwarf"
  collections:
    images: "images"
    videos: "videos"
