version: 1
formatters:
  simple:
    format: '%(asctime)s %(name)-8s %(levelname)-8s %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: dwarf.log

loggers:
  porter:
    level: INFO
    handlers: [console, file]
    propagate: no
  root:
    level: INFO
    handlers: [console, file]
  steward:
    level: INFO
    handlers: [console, file]
  stocker:
    level: INFO
    handlers: [console, file]
  rabbit:
    level: INFO
    handlers: [console, file] 
